[config]
; Pascal classes will be added to this file (will be created from scratch)
pascal_unit=src/ObjectWrappers.pas
; Perl files will be created in this directory
perl_library=lib

; Pascal class to be used inside Perl. TCalculator must exist, Pascal suffix
; will be added to the wrapper class. If no _constructor is passed, then it
; will not be possible to create this class from perl alone (it will only be
; possible to pass it from pascal via MakeSV)
[pascal/TCalculator]
_unit=TestObjects
_constructor=Create
Create=
Add=Double;
Subtract=Double
Multiply=Double
Divide=Double
GetValue=:Double

; Perl class to be used inside Pascal. TPerl prefix will be added
[perl/Calculator]
_constructor=new
new=
add=Double
subtract=Double
multiply=Double
divide=Double
get_value=:Double

